// <auto-generated />
namespace SysPerson.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialcommit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialcommit));
        
        string IMigrationMetadata.Id
        {
            get { return "202204060433227_initial-commit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
